# Generated by Django 4.2.7 on 2024-01-25 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(blank=True, max_length=255, null=True)),
                ('news_title_uz', models.CharField(max_length=255, verbose_name='title_uz')),
                ('news_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='title_en')),
                ('news_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='title_ru')),
                ('news_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('news_desc_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='News_desc_uz')),
                ('news_desc_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='News_desc_en')),
                ('news_desc_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='News_desc_ru')),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name="News's image")),
                ('news_text', models.TextField(blank=True, null=True)),
                ('news_text_uz', models.TextField(verbose_name='Yangilikning toliq matni')),
                ('news_text_en', models.TextField(blank=True, null=True, verbose_name='Yangilikningn inglizcha matni')),
                ('news_text_ru', models.TextField(blank=True, null=True, verbose_name='Yangilikning ruscha matni')),
                ('news_datetime', models.DateTimeField(auto_now_add=True)),
                ('news_views_count', models.IntegerField(default=0, verbose_name='views_count')),
                ('news_source', models.URLField(blank=True, null=True, verbose_name='Manba(agar mavjud bolsa)')),
                ('news_author', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news',
                'ordering': ('-news_datetime',),
            },
        ),
    ]
